analytics: {}
color:
  brandColors:
    - '#f6f7f9'
    - '#17181d'
    - '#9ca574'
    - '#c7c8ca'
    - '#5e605d'
  brandStrength: 0.704392
  lightness: 0.5
  rhythmicContrast: 0.492399
  saturation: 0.511824
cta: {}
layout_spectrum: 0.605574
name: lamariposa
opengraph: {}
purpose: []
typography_spectrum: 0.14645
